{% set name = "scoringrules" %}
{% set version = "0.10.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scoringrules-{{ version }}.tar.gz
  sha256: a92ea7863f0ce09820af3e5e66166de2c65ad06026bafbb45293a84780526e30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.25.0
    - scipy >=1.10.0

test:
  imports:
    - scoringrules
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Scoring rules for probabilistic forecast evaluation.
  home: https://github.com/frazane/scoringrules
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frazane
